import React from "react";
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {GlobalProvider} from "@/app/GlobalProvider";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import 'primeicons/primeicons.css';
import './globals.css';


const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <GlobalProvider>{children}</GlobalProvider>
        </body>
        </html>
    );
}
