import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import React from "react";
import {APIOptions, PrimeReactProvider} from "primereact/api";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import 'primeicons/primeicons.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    const primeReactConfig: Partial<APIOptions> = {
        inputStyle: 'filled',
    };

    return (
        <html lang="en">
        <body className={inter.className}>
        <PrimeReactProvider value={primeReactConfig}>
            {children}
        </PrimeReactProvider>
        </body>
        </html>
    );
}
